version: '3.7'
services:
  web-php:
    image: centurynine/swarm01-web-php:0311
    networks:
     - webproxy
    logging:
      driver: json-file
      options:
        "max-size": "10m"
        "max-file": "5"
    volumes:
      - app:/var/www/html/
    deploy: 
      replicas: 1 
      labels:
        - traefik.docker.network=webproxy
        - traefik.enable=true
        - traefik.http.routers.spcn05-php-https.entrypoints=websecure
        - traefik.http.routers.spcn05-php-https.rule=Host("spcn05-php.xops.ipv9.me")
        - traefik.http.routers.spcn05-php-https.tls.certresolver=default
        - traefik.http.services.spcn05-php.loadbalancer.server.port=80

volumes:
  app:

networks:
  webproxy:
    external: true